load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "impl",
    srcs = [
        "epforwarder.go",
        "epforwarder_mock.go",
        "epforwarder_mockgen.go",
        "params.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/comp/forwarder/eventplatform/impl",
    visibility = ["//visibility:public"],
    deps = [
        "//comp/core/config",
        "//comp/core/diagnose/def",
        "//comp/core/hostname",
        "//comp/core/hostname/hostnameinterface",
        "//comp/core/secrets/def",
        "//comp/core/secrets/noop-impl",
        "//comp/forwarder/eventplatform/def",
        "//comp/forwarder/eventplatformreceiver",
        "//comp/forwarder/eventplatformreceiver/eventplatformreceiverimpl",
        "//comp/logs-library/metrics",
        "//comp/logs-library/sender",
        "//comp/logs-library/sender/http",
        "//comp/logs/agent/config",
        "//comp/serializer/logscompression/def",
        "//pkg/config/env",
        "//pkg/config/model",
        "//pkg/config/setup",
        "//pkg/logs/client",
        "//pkg/logs/client/http",
        "//pkg/logs/message",
        "//pkg/util/compression",
        "//pkg/util/ecs/metadata",
        "//pkg/util/fxutil",
        "//pkg/util/log",
        "//pkg/util/option",
        "//pkg/util/startstop",
        "//pkg/version",
        "@com_github_golang_mock//gomock",
        "@org_uber_go_fx//:fx",
    ],
)

go_test(
    name = "impl_test",
    srcs = ["epforwarder_test.go"],
    embed = [":impl"],
    gotags = ["test"],
    deps = [
        "//comp/core/config",
        "//comp/core/secrets/noop-impl",
        "//comp/forwarder/eventplatformreceiver",
        "//comp/forwarder/eventplatformreceiver/eventplatformreceiverimpl",
        "//comp/logs/agent/config",
        "//comp/serializer/logscompression/def",
        "//comp/serializer/logscompression/fx-mock",
        "//pkg/util/fxutil",
        "@com_github_stretchr_testify//suite",
    ],
)
