load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "mock",
    srcs = ["mock.go"],
    importpath = "github.com/DataDog/datadog-agent/comp/logs/agent/mock",
    visibility = ["//visibility:public"],
    gotags = ["test"],
    deps = [
        "//comp/logs/agent/impl",
        "//pkg/util/fxutil",
    ],
)
