load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "pingicmppermissions",
    srcs = [
        "check.go",
        "check_noop.go",
        "issue.go",
        "module.go",
        "module_noop.go",
    ],
    importpath = "github.com/DataDog/datadog-agent/comp/healthplatform/issues/pingicmppermissions",
    visibility = ["//visibility:public"],
    deps = select({
        "@rules_go//go/platform:aix": [
            "@com_github_datadog_agent_payload_v5//healthplatform",
        ],
        "@rules_go//go/platform:android": [
            "//comp/core/config",
            "//comp/healthplatform/issues",
            "@com_github_datadog_agent_payload_v5//healthplatform",
            "@org_golang_google_protobuf//types/known/structpb",
        ],
        "@rules_go//go/platform:darwin": [
            "@com_github_datadog_agent_payload_v5//healthplatform",
        ],
        "@rules_go//go/platform:dragonfly": [
            "@com_github_datadog_agent_payload_v5//healthplatform",
        ],
        "@rules_go//go/platform:freebsd": [
            "@com_github_datadog_agent_payload_v5//healthplatform",
        ],
        "@rules_go//go/platform:illumos": [
            "@com_github_datadog_agent_payload_v5//healthplatform",
        ],
        "@rules_go//go/platform:ios": [
            "@com_github_datadog_agent_payload_v5//healthplatform",
        ],
        "@rules_go//go/platform:js": [
            "@com_github_datadog_agent_payload_v5//healthplatform",
        ],
        "@rules_go//go/platform:linux": [
            "//comp/core/config",
            "//comp/healthplatform/issues",
            "@com_github_datadog_agent_payload_v5//healthplatform",
            "@org_golang_google_protobuf//types/known/structpb",
        ],
        "@rules_go//go/platform:netbsd": [
            "@com_github_datadog_agent_payload_v5//healthplatform",
        ],
        "@rules_go//go/platform:openbsd": [
            "@com_github_datadog_agent_payload_v5//healthplatform",
        ],
        "@rules_go//go/platform:osx": [
            "@com_github_datadog_agent_payload_v5//healthplatform",
        ],
        "@rules_go//go/platform:plan9": [
            "@com_github_datadog_agent_payload_v5//healthplatform",
        ],
        "@rules_go//go/platform:qnx": [
            "@com_github_datadog_agent_payload_v5//healthplatform",
        ],
        "@rules_go//go/platform:solaris": [
            "@com_github_datadog_agent_payload_v5//healthplatform",
        ],
        "@rules_go//go/platform:windows": [
            "@com_github_datadog_agent_payload_v5//healthplatform",
        ],
        "//conditions:default": [],
    }),
)
